version: '3'
services:
  hello1:
    build: .
    image: toy-flask:local
    environment:
      datadog_agent_host: dd-agent
  hello2:
    image: toy-flask:local
    environment:
      datadog_agent_host: dd-agent
  hello3:
    image: toy-flask:local
    environment:
      datadog_agent_host: dd-agent
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
