version: '3'
services:
  hello1:
    build: .
    image: hello:local
  hello2:
    image: hello:local
  hello3:
    image: hello:local
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
